// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// colSumsCpp
NumericVector colSumsCpp(NumericMatrix x);
RcppExport SEXP _fsusieR_colSumsCpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(colSumsCpp(x));
    return rcpp_result_gen;
END_RCPP
}
// colVarsCpp
NumericVector colVarsCpp(NumericMatrix x);
RcppExport SEXP _fsusieR_colVarsCpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(colVarsCpp(x));
    return rcpp_result_gen;
END_RCPP
}
// covCpp
NumericMatrix covCpp(NumericMatrix x);
RcppExport SEXP _fsusieR_covCpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(covCpp(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fsusieR_colSumsCpp", (DL_FUNC) &_fsusieR_colSumsCpp, 1},
    {"_fsusieR_colVarsCpp", (DL_FUNC) &_fsusieR_colVarsCpp, 1},
    {"_fsusieR_covCpp", (DL_FUNC) &_fsusieR_covCpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_fsusieR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
