#' @title Empirical Bayes multivariate functional regression
#'
#' @description Empirical Bayes multivariate functional regression
#'
#' @details Empirical Bayes multivariate functional regression
#'
#' @param obj an object of class EBmvFR
#' @param W a list in which element D contains matrix of wavelet d coefficients and
#'  element C contains the vector of scaling coefficients
#'
#' @param X matrix of size n by p contains the covariates
#' @param verbose If \code{verbose = TRUE}, the algorithm's progress,
#' and a summary of the optimization settings are printed to the
#' console.
#' @param lowc_wc list of wavelet coefficients that exhibit too little variance
#' @param indx_lst list generated by gen_wavelet_indx for the given level of resolution
#'
#' @param tol Non-negative tolerance for absolute ELBO changes when
#'   \code{cal_obj=TRUE}; otherwise for relative coefficient/noise changes
#'   and absolute mixture-probability changes.
#'
#' @param maxit Maximum number of complete coordinate-ascent sweeps.
#'
#' @param init_pi0_w,control_mixsqp,nullweight,max_step_EM Legacy optimizer
#'   controls retained for call compatibility; the fitting loop uses a
#'   single exact responsibility M-step per sweep.
#' @param cal_obj If TRUE, record and monitor the ELBO, including its initial
#'   value. Otherwise monitor parameter changes.
#' @export

EBmvFR.workhorse <- function(obj,
                             W,
                             X,
                             tol,
                             lowc_wc,
                             init_pi0_w ,
                             control_mixsqp ,
                             indx_lst,
                             nullweight,
                             cal_obj ,
                             verbose,
                             maxit,
                             max_step_EM){
  Y_f <- cbind(W$D, W$C)
  if (verbose) print("Initialization done")
  obj$converged <- FALSE
  obj$niter <- 0L
  obj$residual <- Y_f - X %*% obj$fitted_wc[[1]]
  if (cal_obj) obj$ELBO <- .ebmvfr_objective(obj, Y_f, X)

  for (iter in seq_len(maxit)) {
    previous_mean <- obj$fitted_wc[[1]]
    previous_pi <- unlist(get_pi_G_prior(obj$G_prior))
    previous_sigma2 <- obj$sigma2
    # Recompute once per sweep to limit accumulated rounding error.
    # Within the sweep, only rank-one residual updates are needed.
    obj$residual <- Y_f - X %*% previous_mean
    for (j in seq_len(ncol(X))) {
      if (verbose) print(paste("Fitting effect", j, ", iter", iter))
      obj <- fit_effect.EBmvFR(obj, j, X, W$D, W$C, indx_lst, lowc_wc)
    }

    obj <- update_prior_EBmvFR(obj,
                              max_step = max_step_EM,
                              init_pi0_w = init_pi0_w,
                              control_mixsqp = control_mixsqp,
                              indx_lst = indx_lst,
                              lowc_wc = lowc_wc,
                              nullweight = nullweight)
    obj <- update_residual_variance(
      obj, sigma2 = estimate_residual_variance(obj, Y = Y_f, X = X))

    # Scale-invariant coefficient/noise changes, plus absolute changes in
    # mixture probabilities. Respect the user's tolerance in both modes.
    mean_scale <- max(abs(previous_mean), abs(obj$fitted_wc[[1]]),
                      sqrt(previous_sigma2 / min(obj$d)))
    check <- max(max(abs(obj$fitted_wc[[1]] - previous_mean)) / mean_scale,
                 max(abs(unlist(get_pi_G_prior(obj$G_prior)) - previous_pi)),
                 abs(obj$sigma2 - previous_sigma2) /
                   max(obj$sigma2, previous_sigma2))
    obj <- test_stop_cond(obj, check, cal_obj, Y_f, X, W$D, W$C, indx_lst)
    obj$niter <- iter
    if (obj$check <= tol) {
      obj$converged <- TRUE
      break
    }
  }
  # This cache is only valid within the workhorse and is not an output.
  obj$residual <- NULL
  obj
}
