#' @title Compute KL divergence effect l
#
#' @param obj a susisF object defined by  init_susiF_obj  function
#
#' @param l integer larger or equal to 1. Corresponds to the effect to be accessed
#
#
#' @param X matrix of covariate
#
#' @param D matrix of wavelet D coefficients from the original input data (Y)
#
#' @param C vector of wavelet scaling coefficient from the original input data (Y)
#
#' @param indx_lst list generated by gen_wavelet_indx for the given level of resolution
#
#' @return The KL divergence for effect l
#' @export
#' @keywords internal
cal_KL_l <- function(obj, l, X, D,C , indx_lst, ...)
  UseMethod("cal_KL_l")






#' @title Compute KL divergence for effect l (correct ELBO version)
#'
#' @description
#' Per-effect KL between q_l(b_l, gamma_l) and the prior p(b_l, gamma_l),
#' using the susieR identity
#'   KL(q_l || p_l) = log p(R_l) - E_{q_l}[ log p(R_l | b_l, gamma_l) ]
#'                  = loglik_SFR(R_l) - loglik_SFR_post(R_l)
#' where R_l = Y - X * sum_{k != l} alpha_k * mu_k is the partial residual.
#'
#' This always returns a non-negative quantity at the SER posterior optimum,
#' so the ELBO formed as Eloglik(Y, X) - sum_l KL_l is a valid lower bound.
#'
#' The previous implementation computed
#'   (1/(2 sigma^2)) * (||X E[F]||^2 - sum_j d_j E[F^2_j])
#' which is generically negative and therefore not a KL.
#'
#' @export
#' @keywords internal
cal_KL_l.susiF <- function(obj, l, X, D, C, indx_lst, ...) {

  ## Reconstruct full wavelet-domain Y from detail (D) and scaling (C) coefs.
  Y <- cbind(D, C)

  ## Partial residual R_l = Y - X * sum_{k != l} alpha_k * mu_k.
  if (obj$L > 1) {
    other_F <- matrix(0, nrow = ncol(X), ncol = ncol(Y))
    for (k in seq_len(obj$L)) {
      if (k != l) {
        other_F <- other_F + obj$alpha[[k]] * obj$fitted_wc[[k]]
      }
    }
    R_l <- Y - X %*% other_F
  } else {
    R_l <- Y
  }

  log_marg <- loglik_SFR     (obj, l, Y = R_l, X = X, indx_lst = indx_lst)
  log_post <- loglik_SFR_post(obj, l, Y = R_l, X = X)

  out <- log_marg - log_post
  ## Numerical floor: at the SER optimum out >= 0 in exact arithmetic.
  if (!is.finite(out)) return(0)
  max(out, 0)
}


#' @title Compute log likelihood of single function regression of effect l
#
#' @param obj a susiF object defined by  init_susiF_obj  function
#
#' @param l effect to update
#
#' @param Y wavelet transformed phenotype
#
#' @param X Matrix of covariates
#' @param indx_lst list generated by gen_wavelet_indx for the given level of resolution
#
#
#' @return The log-likelihood, \eqn{\log p(Y | X, V)}, where V is the prior parameters
#' @export
#' @keywords internal
loglik_SFR <- function    (obj, l,  ...)
  UseMethod("loglik_SFR")

#' @rdname loglik_SFR
#
#' @method loglik_SFR susiF
#
#' @importFrom stats dnorm
#
#' @export loglik_SFR.susiF
#
#' @export
#' @keywords internal
loglik_SFR.susiF <- function (obj, l, Y , X, indx_lst, ...)
{
  lBF            <- get_lBF(obj,l)
  prior_weights  <- rep(1/ncol(X),ncol(X))
  maxlBF         <- max(lBF)
  w              <- exp(lBF - maxlBF)
  w_weighted     <- w * prior_weights
  weighted_sum_w <- sum(w_weighted)
  lBF_model      <- maxlBF + log(weighted_sum_w)
  return(lBF_model + sum(dnorm(Y,0,sd = sqrt(obj$sigma2),log = TRUE)))
}


#' @title Compute posterior expected loglikelihood for single function
#   regression of effect l
#
#' @param obj susiF object, for example created by calling
#'  init_susiF_obj .
#
#' @param l Index of effect to update.
#
#' @param \dots Other arguments.
#
#' @return Posterior expected log-likelihood for the single-function
#   regression of effect l.
#
#' @export
#' @keywords internal
loglik_SFR_post <- function (obj, l, ...)
  UseMethod("loglik_SFR_post")

#' @rdname loglik_SFR_post
#
#' @param Y Wavelet-transformed phenotype.
#
#' @param X Matrix of covariates.
#
#' @method loglik_SFR_post susiF
#
#' @export loglik_SFR_post.susiF
#
#' @export
#' @keywords internal
loglik_SFR_post.susiF <- function (obj, l, Y, X, ...)
{
  ## E_{q_l}[ log p(Y | X, b_l, gamma_l) ] for the single-effect SuSiE model.
  ##
  ## Under q_l, gamma_l selects exactly one component, so cross terms in
  ## E_q[(X b_l)^2] vanish and
  ##   E_q[||Y - X b_l||^2]
  ##     = ||Y||^2 - 2 sum(Y * (X * E[b_l])) + sum_t sum_j d_j * E[b^2_l][j,t]
  ## with E[b_l]   = alpha_l * mu_l        (= get_post_F (obj, l)),
  ##      E[b^2_l] = alpha_l * (mu^2 + s2_post)  (= get_post_F2(obj, l)),
  ##      d_j      = ||X[,j]||^2.
  ##
  ## The previous version used `s2/2` (should be `1/(2*s2)`) and
  ## `sum(t(EF2) %*% EF2)` (should be `sum(d * EF2)`); both are corrected here.

  n   <- nrow(Y)
  t   <- ncol(Y)
  EF  <- get_post_F (obj, l)              # p x t
  EF2 <- get_post_F2(obj, l)              # p x t
  s2  <- obj$sigma2

  d <- attr(X, "d")
  if (is.null(d)) d <- rep(nrow(X) - 1, ncol(X))

  e_quad <- sum(Y * Y) - 2 * sum(Y * (X %*% EF)) + sum(d * EF2)

  return(-(n * t / 2) * log(2 * pi * s2) - e_quad / (2 * s2))
}




#' @title Expected log likelihood for a   susiF   object
#
#' @param obj a susiF object defined by  init_susiF_obj  function
#
#' @param Y Matrix of outcomes
#
#' @param X Matrix of covariates
#'
#' @param \dots Other arguments.
#
#' @return Expected log likelihood
#' @export
#' @keywords internal
Eloglik <- function    (obj,   ...)
  UseMethod("Eloglik")


#' @rdname Eloglik
#
#' @method Eloglik susiF
#
#' @export Eloglik.susiF
#' @export
#' @keywords internal
Eloglik.susiF = function (obj,Y ,X,  ...) {
  n = nrow(Y)
  t = ncol(Y)

  return(-(n*t/2) * log(2*pi*obj$sigma2) - (1/(2*obj$sigma2)) * get_ER2( obj, Y, X))
}
#  @export
#  @keywords internal
#Eloglik.susiF_ss = function (obj,data,...) {
#  n <- data$N
#  t <- ncol(data$Bhat)
#
#  return(-(n*t/2) * log(2*pi*obj$sigma2) - (1/(2*obj$sigma2)) * get_ER2( obj,data))
#}

#' @title Get objective function from data and susiF object
#
#' @param obj a susiF object defined by  init_susiF_obj  function
#
#' @param Y Matrix of outcomes
#
#' @param X matrix of covariate
#
#' @param D matrix of wavelet D coefficients from the original input data (Y)
#
#' @param C vector of wavelet scaling coefficient from the original input data (Y)
#
#' @param indx_lst list generated by gen_wavelet_indx for the given level of resolution
#
#' @return objective function value
#
#' @export
#' @keywords internal
get_objective <- function    (obj,  Y, X, D, C , indx_lst,  ...)
  UseMethod("get_objective")


#' @rdname get_objective
#
#' @method get_objective susiF
#
#' @export get_objective.susiF
#' @export
#' @keywords internal
get_objective.susiF <- function    (obj, Y, X, D, C , indx_lst,  ...)
{
  ## ELBO = E_q[log p(Y | X, beta)] - sum_l KL(q_l || p_l)
  ## With the corrected cal_KL_l.susiF, obj$KL[l] >= 0 holds at the optimum,
  ## so this expression is a proper lower bound on log p(Y | X).
  ##
  ## Previously the Eloglik(...) call was commented out, leaving just
  ## sum(obj$KL); that was a sign-and-structure mismatch with the rest
  ## of the IBSS update.

  return(Eloglik(obj, Y, X) - sum(obj$KL))
}

