# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

colSumsCpp <- function(x) {
    .Call('_fsusieR_colSumsCpp', PACKAGE = 'fsusieR', x)
}

colVarsCpp <- function(x) {
    .Call('_fsusieR_colVarsCpp', PACKAGE = 'fsusieR', x)
}

covCpp <- function(x) {
    .Call('_fsusieR_covCpp', PACKAGE = 'fsusieR', x)
}

