name: Update documentation

on:
  push:
    branches: [main]
    paths:
      - 'vignettes/**'
      - 'R/**'
      - 'man/**'
      - '_pkgdown.yml'
      - 'DESCRIPTION'
  pull_request:
    branches: [main]
    paths:
      - 'vignettes/**'
      - 'R/**'
      - 'man/**'
      - '_pkgdown.yml'
      - 'DESCRIPTION'
  workflow_dispatch:

jobs:
  update_documentation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Create TOML from recipe
        run: .github/workflows/create_toml_from_yaml.sh

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.9.0

      - name: Build package documentation
        run: pixi run devtools_document

      - name: Build pkgdown site
        run: pixi run pkgdown_build

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          clean: false
          branch: gh-pages
          folder: docs